### ISSUE TITLE
problem with deployment

### ISSUE THREAD

**Issue by krobasky** [RENCI/fuse-tool-cellfie#8]
When I clone, create the .env, create the volume, add a submitter and click 'execute', I get the following error.

Is there anything else that I need to do? Are the defaults sufficient?

```
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8087 (Press CTRL+C to quit)
2022-04-05 01:43:42,217 | DEBUG | main:analyze | submitter_id: f@b.com
INFO:     172.18.0.1:56382 - "POST /submit?submitter_id=f%40b.com HTTP/1.1" 404 Not Found
2022-04-05 01:43:53,487 | ERROR | main:analyze | Command '/data/e8d7bdb7/geneBySampleMatrix.csv 32 MT_recon_2_2_entrez.mat local value 5 minmaxmean 5 5 /data/e8d7bdb7' in image 'hmasson/cellfie-standalone-app:v2' returned non-zero exit status 249: b"Error using load\nUnable to read file 'taskStructure'. No such file or directory.\n\nError in CellFie (line 97)\n\nError in execCellfie (line 46)\n\nMATLAB:load:couldNotReadFile\n"
Traceback (most recent call last):
  File "/app/src/main/python/./main.py", line 122, in analyze
    cellfie_container_logs = client.containers.run(image, volumes=volumes, name=task_id, working_dir="/input", privileged=True, remove=True, command=command, detach=False)
  File "/usr/local/lib/python3.10/site-packages/docker/models/containers.py", line 848, in run
    raise ContainerError(
docker.errors.ContainerError: Command '/data/e8d7bdb7/geneBySampleMatrix.csv 32 MT_recon_2_2_entrez.mat local value 5 minmaxmean 5 5 /data/e8d7bdb7' in image 'hmasson/cellfie-standalone-app:v2' returned non-zero exit status 249: b"Error using load\nUnable to read file 'taskStructure'. No such file or directory.\n\nError in CellFie (line 97)\n\nError in execCellfie (line 46)\n\nMATLAB:load:couldNotReadFile\n"
2022-04-05 01:43:53,488 | DEBUG | main:analyze | run duration: (0, 11)
2022-04-05 01:43:53,488 | INFO | main:get_results | reading: /app/data/e8d7bdb7/detailScoring.csv
```

**Comment by krobasky** [comment]
Jason helped me figure out how to get this deployed on my desktop, but the readme still needs a lot of work. One thing that's missing is what the busybox output SHOULD look like. If we can get all this information captured onto the README, I think we can avoid future deployment issues. I'm reassigning this to Shalki. 
Shalki, if you're able to deploy this on your own machine by following the directions and repeatedly analyze a gene expression file without any issues after deploying by your own directions, you can close this ticket.
